synopse/mORMot2

src/net/mormot.net.sock.pas

This fix a situation 
```
ServerSock := TCrtSocket.Bind(fPort, cslTCP, 0); // set timeout to 0 to wait on read loop until closed
AcceptedSocket := ServerSock.AcceptIncoming(); // AcceptedSocket.timeout is 10000 (default) but should be 0
```

lets accepted socket inherit timeout value from binded one

---

src/db/mormot.db.rad.firedac.pas

Compilation under Delphi 10.3.3 stops with:
[dcc32 Error] mormot.db.rad.firedac.pas(322): E2003 Undeclared identifier: 'TDynArray'
Adding mormot.core.data, to the uses clause solves it

Add missing unit

---

.gitignore
get_latest_static.sh
test/build_fpc.sh

- added script to build tests under Linux
- script to update static asset to latest
Changes compared to Windows build scripts:
- I use UPPERCASE for env variables what can be passed from outside word - this is a naming convention in Unix.
- in  `get_latest_static.sh` I can't use a https://api.github.com/repos/synopse/mORMot2/releases/latest API call because of "pre-releaes" not works in this way, so I parse a JSON to get a latest pre-release
- I use `build` instead of `compil` for naming a build script
Having such a scripts allows to setup a github action in future for CI 
Verifed on Ubuntu 20.04

added script to build tests under Linux

---

src/lib/mormot.lib.curl.pas
src/net/mormot.net.client.pas

Back-port from https://github.com/synopse/mORMot/pull/376 with subsequent changes.
Also added misisng in mORMot2 call of curl.global_cleanup in TLibCurl destructor to ensure all shared resources are disposed correctly (sockets are closed, for example)

added share interface support for LibCurl (back-port form mORMot1 pr376)

---

src/orm/mormot.orm.server.pas

t is of PtrInt and if fModel.Tables=0 under Delphi XE6 Win64 fTrackChangesHistoryTableIndex[t] := -1; is called with t=0

av in case of empty Model

---

src/core/mormot.core.data.pas

TDynArray.Copy: Do not dereference PDynArray arguments when passing them to DynArrayCopy, they might be nil and cause an access violation.
I encountered this issue when TSQLPropInfoRTTIDynArray.CopySameClassProp tried to copy a TRawUTF8DynArray where both src and dst were empty.

TDynArray.Copy: Do not dereference PDynArray arguments

---

src/orm/mormot.orm.core.pas

Calling OrmProps directly returned props for TOrm, not the actual instance class OrmProps. 
I noticed it because the TOrm class doesn't have any fields, so I got an access violation when the method was called from `mormot.core.json._JS_RttiCustom` (`TOnRttiJsonWrite(nfo.fJsonWriter)(c.W, Data, c.Options)`).

Use correct ORM props in TOrm.RttiJsonWrite.

---

src/net/mormot.net.http.pas

For HTTP 1.1 default behavior is keep-alive connection even if  `Connetion: keep-alive` header is missing
with wrk after fix I got ~80000 RPS compared to ~17000 RPS before fix. also verified with curl:
- before fix - wrong connection closing
```
$ curl -v http://localhost:8888/echo
*   Trying 127.0.0.1:8888...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET /echo HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: mORMot2 (Linux)
< X-Powered-By: mORMot 2 synopse.info
< Content-Length: 35
< Connection: Close
< 
* Closing connection 0
```
- after fix: valid behavior for bot 1.1 and 1.0
```
$ curl -v http://localhost:8888/echo
*   Trying …
```

fix keep-alive for HTTP 1.1

---

src/core/mormot.core.interfaces.pas
src/rest/mormot.rest.client.pas
src/rest/mormot.rest.mvc.pas
src/rest/mormot.rest.server.pas
src/soa/mormot.soa.core.pas
test/test.soa.core.pas
test/test.soa.network.pas

Reverts synopse/mORMot2#72
Code added into `TRestServerUriContext.ExecuteSoaByMethod` slows down execution of regular methods, and I am not sure it is very stable about the actual methods process.

Revert "ServiceUndefine/DeleteInterface implementation and TestCase."

---

get_latest_static.sh
src/rest/mormot.rest.http.server.pas

Fix output directory for the extraction of downloaded static files and make sure ONLYUSEHTTPSOCKET is honored in mormot.rest.http.server

Fix output directory for the extraction of downloaded static files and make sure ONLYUSEHTTPSOCKET is honored in mormot.rest.http.server.

---

src/core/mormot.core.os.windows.inc

Utf8ToConsoleDoConv does not set code page for resulting RawByteString, so system.write tries to convert ANSI -> Unicode -> OEM, and prints nothing.
Also, "no conversion needed" is not true. It's converted ANSI -> Unicode -> OEM, but conversion succeeded.
```
function Utf8ToConsole(const S: RawUtf8): RawByteString;
begin
if IsAnsiCompatible(S) then
result := S // conversion in system.write: ANSI -> Unicode -> OEM
else
Utf8ToConsoleDoConv(S, result);
end;
```

Fix Utf8ToConsole to work with non-ascii characters

---

src/lib/mormot.lib.openssl11.pas

IntToHex = string, OpenSslVersionHexa = string

compiler warning under Delphi 10.4

---

src/net/mormot.net.http.pas

The idea is to move most useful headers up in IdemPPChar array.
This decrease CPU time spend in ParseHeader function from 17.5% to 15.9% (measured on /json TFB test using valgrind) and should help a little on real-life browser request.
/json RPS improved by 0.4%  ~500000 -> ~504000

Improve HTTP header parser

---

src/net/mormot.net.http.pas

SSE based PosChar is faster compared to optimized pascal code. 
On TFB `/json` endpoint this version works 5.6% of time vs 10.1% (according to valgrind profile)
May be it break  chunked parsing (not tested) - please, use this PR as an idea of how improve `ProcessParseLine`

use SSE based PosChar for HTTP header parsing

---

src/db/mormot.db.sql.postgres.pas

`StrLen` is twice faster compared to `PQGetLength` 0.2% vs 0.4% on TFB `/db`

prefer mORMot StrLen over PQGetLength + prevent unnecessary PQGetIsNull calls

---

src/db/mormot.db.sql.postgres.pas

Postgres: use StrLen only for small buffers, else PQ.GetLength

---

src/core/mormot.core.os.pas
src/lib/mormot.lib.openssl11.pas
src/net/mormot.net.acme.pas

Some small fixes after refactoring.
About EccGetPubKey. Instead of EC_KEY_key2buf you can use EC_KEY_get0_public_key + EC_KEY_get0_group + EC_POINT_point2buf.

Fixes for ACME client

---

src/net/mormot.net.acme.pas

On my Ubuntu 18.04 HEAD request to Directory URL returns empty body. So I changed to GET and now it works.

TAcmeClient fixes

---

src/core/mormot.core.base.pas

When Str is empty, StartPos  assigned value 0, and last line failed with AV:
`FastSetString(result, @PByteArray(Str)[-1], 1)`

Fix Split when Str is empty

---

src/net/mormot.net.ws.async.pas
src/net/mormot.net.ws.server.pas

Websocket connection over HTTPS does not work (returns 404) because hsrHttps is missing in Ctxt.ConnectionFlags and TRestHttpServer.Request cannot find REST server instance (in `if (Security in SEC_TLS) = tls then...`). 
This patch changes ComputeContext to include hsrHttps in ConnectionFlags.
Not sure if we need to do this in TWebSocketProcessClient.ComputeContext.

Fix Websocket over HTTPS

---

src/orm/mormot.orm.base.pas

optimize Postgres bulk update  by updating table in primary key order to minimize locks

optimize Postgres bulk update 

---

ex/techempower-bench/raw.pas
src/db/mormot.db.raw.postgres.pas
src/db/mormot.db.sql.postgres.pas

- PostgreSQL pipeline mode has been rethought - better to use Flush after each statement instead of PipelineSync after last statement; In this case server starts to execute queries ASAP;
- TFB `/rawupdates` - use `::bigint[]` instead of `::NUMERIC[]` typecast (NUMERIC is a floating point type, but we need Int64); added `order by id` to minimize locks waits (as in ORM)

Solved TFB /rawqueries and /rawupdates performance problems

---

src/core/mormot.core.os.posix.inc

Function `RunUntilSigTerminatedPidFile` incorrectly returns a pid file in /tmp folder, even if app path is writeable, because when called with `ensureWritable = false` and if pid file does not exists, `Result` variable is modified and next `IsDirectoryWritable` called with wrong path.
I think previously `RunUntilSigTerminatedPidFile` was called from `RunUntilSigTerminated` with `ensureWritable = true` and worked fine.

Fix RunUntilSigTerminatedPidFile

---

ex/techempower-bench/raw.pas

use ? as params placeholders as expected by mORMot DB layer
Since performance is the same I propose to revert to sub-select version as more realistic

tfb example: fixed rawupdates

---

ex/techempower-bench/raw.lpi
ex/techempower-bench/raw.pas

- allow 2 thread per server in manual mode (instead of 16 min)
- use several servers for CPU>=12 (instead of > 12)

TFB bench: more flexible threads tuning

---

src/db/mormot.db.raw.postgres.pas
src/db/mormot.db.sql.postgres.pas

This MR break parameters logging, since I rewrite a p^.VInt64 value to be in htonl byte order as required by PG binary protocol. 
Can we extend a TSqlDBParam by adding VInt64BE, because comment below say don't to extend....  
```
// - don't change this structure, since it will be serialized as binary
// for TSqlDBProxyConnectionCommandExecute
TSqlDBParam = packed record
```

Postgres: bind int4 and int8 parameters as binary

---

src/core/mormot.core.zip.pas

- Unzip('dir/file.txt', 'outdir') was extracting the file at 'outdirdir/file.txt' instead of 'outdir/dir/file.txt'

Fix TZipRead unzip when DestDir has no end path delimiter

---

src/net/mormot.net.async.pas

This allow direct access to the internal AsyncConnectionsThread's.
I need it to verify idea for TFB test about set all threads of each server instance to the same CPU
So we will have 28 servers each with 8 threads, all 8 threads of server 0 is binds to the 0, all 8 threads for server 1 - to 1 core and so on
From my tests (on my server hardware) it's improve all tests a little, but json - for +15%!

TAsyncConnections: allow direct access to the internal threads

---

ex/techempower-bench/README.md
ex/techempower-bench/raw.pas
packages/lazarus/mormot2.pas

- use accessible CPUs (can be limited by taskset) instead of available
- added named command line parameters for servers (-s), threads )-t) and CPU pinning (-p)
- added pinning servers to CPUs
- change rawupdates to use `update table set .. from values (), (), ... where id = id`

CPU pinning with limited CPUs support 

---

src/db/mormot.db.core.pas
src/db/mormot.db.sql.pas
src/db/mormot.db.sql.zeos.pas

MariaDB supports SQL commands in a way that Mysql does not: ex. IF EXISTS in CREATE INDEX 
MariaDB is now added in zeos 8.0 as an additional protocol.

 Support for dMariaDB type of database server for zeos

---

src/core/mormot.core.os.pas

With a command line like this:
```sh
binary --parameter 0 --parameter 1
```
A call to `Get(['parameter'], utf8DynArray)` was creating an infinite loop

Fix infinite loop when using multiple times the same parameter

---

src/net/mormot.net.http.pas

As discussed in #203, here's the change to add the JSON:API media type "application/vnd.api+json" to the _CONTENTAPP array to allow compression

Added JSON:API media type to allow compression

---

src/core/mormot.core.text.pas

While try to use this function in mORMot1 my first attempt was invalid, because I'm not expect  what result is in "reverse" order. Better to note this in documentation for mROMot2

improve IPToCardinal doc to avoid confusion

---

src/core/mormot.core.os.pas
src/core/mormot.core.os.windows.inc

Small change, default const params for Username and Password provide full backward-compatibility.

Pass optional UserName&Password params to Service Install

---

src/core/mormot.core.rtti.pas

bug present in stable, trunk.
TRttiInfo.ComputeCache method assumes Cache parameter will be zeroed out by caller but this is not true because of usage of out prefix which discards initial value. The method does not correctly initialize Cache structure therefor it contains whatever garbage is currently on the stack. The only time out parameter would "work" is if Cache would contain another managed type field which would force the compiler to initialize the structure on method entry.
Fix by using var prefix so that Cache is passed as reference. To be honest because of importance of this method in RTTI generation I would not leave it up to the caller to correctly initialize the Cache record. I would still use out parameter but the first line should be `Default(Cache);` so that it zeroes out …

Fixed critical rtti cache bug

---

src/core/mormot.core.buffers.pas

The changes in this commit https://github.com/synopse/mORMot2/commit/c27ec5dc547f9ef0b48e3b24aeaa285051f5afd1
Introduced a bug in UrlDecodeInt64, which returns the opposite sign of a value.

Fix UrlDecodeInt64

---

src/lib/mormot.lib.gdiplus.pas
src/ui/mormot.ui.gdiplus.pas

See a455fd3e "SynGdiPlus: add support for image attributes" on the v1 repo.

mormot: reintroduced dropped DrawAntiAliased() for mormot2

---

src/core/mormot.core.unicode.pas

This patch is a bit dated and I forgot the details how I ran into the issue :\
It probably was a tab?
Hopefully the fix is obvious to the reviewer ;)

mormot: fix off-by-one in FindNameValue()

---

src/core/mormot.core.os.pas

Random32 returns cardinal and this can cause overflow to a 32bit integer _TmpCounter.

Can cause exception when setting the counter

---

src/core/mormot.core.buffers.pas

I have added the dicom files' mime type. 
The Magic bytes for the file type is from here: https://dicom.nema.org/medical/dicom/current/output/chtml/part10/chapter_7.html
I have included the usually used file extensions: .DCM & .DICOM The extension .DIC was used more in the past but this extension can be used for other types of files and I did not included it. 
I am not sure about the position of new file extensions in MIME_EXT. Please check it and corrected it if needed.

Include Dicom to mime types

---

src/db/mormot.db.sql.odbc.pas
src/lib/mormot.lib.gdiplus.pas

The indentation hints the else block should be one statement, but there are two. Compiling in Delphi 12 it shows a hint there

Bugfix: lacking a begin..end block

---

src/net/mormot.net.openapi.pas

Fixed the memory leaks and some inattention errors.
Don't know if my usage of IJsonClient is valid but at least the generated units compiles and the Rtti registers in the initialization does not raise any errors.
I still have to handle array of array types and default values in the method parameters but since you're also working on this unit I prefer to do small PRs ;)

OpenApi new ExportToDirectory method and fixes

---

src/mormot.defines.inc

Compiling with FPC 3.2.2 is causing a large number of repeated warnings:
```
...\mormot.defines.inc(146,4) Warning: Illegal identifier "6060" for $WARN directive
```
That's because the relevant warning (and the mechanism to analyze `case`, we call it [case analysis in CGE coding conventions](https://castle-engine.io/coding_conventions#case_analysis)) is only in FPC 3.3.1. So using `{$WARN 6060 off}` is only allowed (without the compiler complaining) since FPC 3.3.1.
This proposed PR avoids the warning for older FPC version. 
(This PR makes assumption that FPC older than 3.2.x is not supported by mORMot 2 at all -- if they are, then a different check for FPC version is needed.)

Deal with warning 6060 only since FPC 3.3.1

---

src/db/mormot.db.raw.sqlite3.static.pas

The `memchr` function directive was misaligned with the 64-bit configuration, leading to an unsatisfied forward or external declaration error. (temporary fix #306)

sqlite3: fix Delphi 64-bit compilation error

---

src/rest/mormot.rest.http.server.pas

- Ensure that the OnWSClose() is called regardless of whether the client connection is disconnected normally or abnormally

net: Fixed OnWSClose() sometimes not being called normally

---

src/core/mormot.core.os.pas

Fix for undefined declaration for 'Win32DotNetExceptions' when using "NOEXCEPTIONINTERCEPT"

Fix undefined Win32DotNetExceptions when using NOEXCEPTIONINTERCEPT

---

src/core/mormot.core.log.pas

Hello @synopse 
The latest update to the core.log has some forgotten unwrapped code for NOEXC
like
https://github.com/synopse/mORMot2/blob/dd4376c74344820c20567a2acfa2b8a6f07407e3/src/core/mormot.core.log.pas#L4161
https://github.com/synopse/mORMot2/blob/dd4376c74344820c20567a2acfa2b8a6f07407e3/src/core/mormot.core.log.pas#L4619

Fix compiling error when NOEXCEPTIONINTERCEPT is used

---

src/soa/mormot.soa.codegen.pas

Using a record like this:
```delphi
type
TMyRecord =
packed record
SomeUnimportantData1: Integer;
SomeUnimportantData2: Integer;
Res: array [1..66] of AnsiChar;
end;
```
... crashes in `TWrapperContext.ContextNestedProperties`, when it's called from `TRestServerUriContext.ExecuteSoaByMethod`.
Looking at the code,
- the `rtti := rtti.ArrayRtti` is executed for  `TMyRecord.Res` field,
- but the `rtti.ArrayRtti` given (by Delphi 12.1) is `nil`.
- So the code crashes when it tries to access `rtti.Props.Count`, since `rtti` is `nil`.
I made a simple fix that does solve the issue in our case.
It seems it's a regression caused by https://github.com/synopse/mORMot2/commit/8047afbf24d57ce20ee9143811045f2687c62f31 , which added using `ArrayRtti`? Old versions of mORMot (from ~2 years ago) don't …

Fix: TWrapperContext.ContextNestedProperties crashes when being used with `packed record` with an array of AnsiChar

---

src/net/mormot.net.ldap.pas

This Pull Requests contains modification to mormot.net.ldap. It fixes the delete method of TLdapClient. With the deleteChildren parameter to true, children of an object wasn't retrieved due to missplaced argument in search method (placed in filter parameter instead of baseDN). Fixed by adding an empty filter, then the baseDN.

ldap: Fixed delete children in non-leaf objects

---

src/core/mormot.core.buffers.pas

This fix restores the PDF image embedding which is currently called in a wrong parameter order where `width` and `height` are switched.
In `TPdfImage.CreateJpegDirect()`:
```pas
if not GetJpegSize(aJpegFile.Memory, len, fPixelWidth, fPixelHeight, bits) then
```
but the function is declared as:
```pas
function GetJpegSize(jpeg: PAnsiChar; len: PtrInt; out Height, Width, Bits: integer)
```
The function declaration should be fixed as the order in the old mormot `SynPDF` unit was also `width` before `height` which also is the typical order of those parameters.

Fix declaration of GetJpegSize() which is called in a wrong parameter order
