synopse/mORMot2

- src/db/mormot.db.sql.odbc.pas
see https://github.com/synopse/mORMot/pull/359
> SQL Server ODBC: set length for varchar parameters

- src/core/mormot.core.json.pas
Port of  mORMot1 #391
see https://synopse.info/forum/viewtopic.php?pid=34934#p34934
> use the same pattern for Date and DateTime serialization

- ex/ThirdPartyDemos/martin-doyle/01-StandAloneORM/src/Project01.lpi
- ex/ThirdPartyDemos/martin-doyle/02-HttpClientServerORM/src/Project02Client.lpi
- ex/ThirdPartyDemos/martin-doyle/02-HttpClientServerORM/src/Project02Server.lpi
- ex/ThirdPartyDemos/martin-doyle/03-MethodBasedServices/src/Project03MethodBasedClient.lpi
- ex/ThirdPartyDemos/martin-doyle/03-MethodBasedServices/src/Project03MethodBasedServer.lpi
- ex/ThirdPartyDemos/martin-doyle/04-InterfacedBasedServices/src/Project04InterfaceBasedClient.lpi
- ex/ThirdPartyDemos/martin-doyle/04-InterfacedBasedServices/src/Project04InterfaceBasedServer.lpi
- ex/ThirdPartyDemos/martin-doyle/05-HttpDaemonORM/src/Project05HttpClient.lpi
- ex/ThirdPartyDemos/martin-doyle/05-HttpDaemonORM/src/Project05HttpDaemon.lpi
- ex/ThirdPartyDemos/martin-doyle/06-DomainDrivenDesign/src/Project06DDDClient.lpi
- ex/ThirdPartyDemos/martin-doyle/06-DomainDrivenDesign/src/Project06DDDServer.lpi
- ex/ThirdPartyDemos/martin-doyle/07-HttpDockerORM/src/Project07HttpClient.lpi
- ex/ThirdPartyDemos/martin-doyle/07-HttpDockerORM/src/Project07HttpDaemon.lpi
- Add crypt directory to the project path
- Remove PUREPASCAL flag
> BUGFIX - some fpc project adjustments

- ex/mvc-blog/MVCModel.pas
- ex/mvc-blog/MVCServerFirebirdIbx.dpr
- ex/mvc-blog/MVCServerFirebirdIbx.lpi
- ex/mvc-blog/MVCServerFirebirdZeos.dpr
- ex/mvc-blog/MVCServerFirebirdZeos.lpi
- ex/mvc-blog/MVCViewModel.pas
- ex/mvc-blog/exe/Views/ArticleView.html
- src/db/mormot.db.sql.ibx.pas
- src/orm/mormot.orm.sql.pas
- IBX driver implement ColumnsToJson and bugfix
- Add Zeos and Ibx project for mvc-blog example and some bugfix
> - IBX driver implement ColumnsToJson and bugfix

- README.md
First OpenSource contribution ;)
> Update README.md Rename => Sydney to Alexandria

- ex/extdb-bench/PerfTestCases.pas
- src/db/mormot.db.sql.ibx.pas
- Implement Firebird 4 IBatch interface for Batch Insert and Update
- Some fixes for current trunk and performance
> - Implement Firebird 4 IBatch interface for Batch Insert and Update

- src/core/mormot.core.variants.pas
https://synopse.info/forum/viewtopic.php?id=6180
> fix regression after 96c8a5d3

- ex/ThirdPartyDemos/martin-doyle/03-MethodBasedServices/src/server.pas
Add dependency
Use exact context input variable.
> Some minor fixes

- src/db/mormot.db.nosql.bson.pas
'$db:aDBName,' has to added in Sections part of OP_MSG
> update for new wire protocol

- src/db/mormot.db.nosql.mongodb.pas
It's just a starting use case for command 'buildinfo'.
Reply looks good, but I stuck at  TMongoReplyCursor.AppendAllToDocVariantDynArray where BsonToDoc(b has a invalid Kind of 48)
> update to start with OP_MSG

- src/db/mormot.db.nosql.mongodb.pas
solved issue with wrong fFirstDocument in my last PR
> update for reply msg

- src/ui/mormot.ui.pdf.pas
- src/ui/mormot.ui.report.pas
mormot.ui.pdf
-----------------------------------
add missing PDF_PERMISSION defines
mormot.ui.report
-----------------------------------
fix uses units
DrawEmfGdip replaced by DrawAntiAliased in line 2857 add TPdfALevel varient in line 4768
TMetaCanvas.RenderMetaFile replaced by RenderMetaFile in line 4805
Signed-off-by: uian2000 <uian2000@gmail.com>
> port mORMotReport to mormot2 mormot.ui.report

- src/app/mormot.app.daemon.pas
- src/core/mormot.core.json.pas
Add the possibility to define the section name when saving in INI file the Tdaemon Settings
> Customized Section for INI file

- ex/techempower-bench/raw.pas
- src/db/mormot.db.raw.postgres.pas
- src/db/mormot.db.sql.postgres.pas
Added support for PostgresSQL pipelining mode (sync)
> added support for PostgresSQL pipelining mode (sync)

- ex/techempower-bench/raw.pas
fix TFB requirements: for URI queries=0 program must use 1 query
> fix TFB requirements for URI queries=0 program must use 1 query

- packages/lazarus/mormot2.lpk
- packages/lazarus/mormot2.pas
- src/misc/README.md
- src/misc/mormot.misc.pecoff.pas
New cross platform TSynPELoader high level class to parse PE files (.exe, .dll, ...)
> Introduce TSynPELoader

- src/net/mormot.net.ldap.pas
- Introduce TLdapResult objectSID and objectGUID helpers
- Fix Search attributes iteration
> Introduce TLdapClient SearchFirst and AddComputer methods

- src/net/mormot.net.ldap.pas
Introduce new methods:
- SearchObject
- GetWellKnownObjectDN
- Connected
And new property **RootDN**
> Enhanced TLdapClient

- src/rest/mormot.rest.server.pas
Include mormot.core.text to call HexToBin function
> Include mormot.core.text

- src/net/mormot.net.ldap.pas
- Also change TLdapResult CopyObjectSid method
> Introduce TLdapClient NETBIOSDomainName property

- src/db/mormot.db.nosql.mongodb.pas
> enable mORMot2 to read from secondary MongoDB

- src/net/mormot.net.ldap.pas
> Introduce TLdapClient.DomainName property

- src/net/mormot.net.ldap.pas
- Also explicitly set TLdapAttribute.GetReadable result codepage to utf8
> Published LdapClient GetErrorString class method

- src/net/mormot.net.ldap.pas
- Previous search for existing computer was invalid
> Fix TLdapClient AddComputer method

- ex/techempower-bench/raw.pas
- added output of connection distribution across servers for multi-server mode
- added output of witch server pinned to witch CPU (for debugging of taskset -c 1,3,5,7 ... case)
> TFB example: console out improved

- src/core/mormot.core.os.pas
Before changes
```
raw [options] [params]
TFB Server using mORMot 2
[options]
-p --pin:
pin each server to a CPU
--nopin:
disable the CPU pinning
-? --help:
display this message
[params]
-s --servers <count> (default 12):
count of servers (listener sockets)
-t --threads <size> (default 8):
per-server thread pool size
```
After changes
```
TFB Server using mORMot 2
Usage: raw [options] [params]
Options:
-p, --pin           pin each server to a CPU
--nopin         disable the CPU pinning
-?, --help          display this message
Params:
-s, --servers <count> (default 12)
count of servers (listener sockets)
-t, --threads <size> (default 8)
per-server thread pool size
```
> Unix-way of formating command line help message

- ex/techempower-bench/raw.pas
- removed unneeded Flush in rawqueries;
- added connection distribution output on shutdown
- cached cache table pointer
> Sync with current TFB sources:

- src/net/mormot.net.ldap.pas
- Fix Result of the compare  function, was always returning False
- Add a Check to verify if the user is connected (bind is not necessary) before sending the compare request
- Use DN in InfoFilter function
> Some fixes about LdapClient of mormot.net.ldap

- src/ui/mormot.ui.pdf.pas
Discussed on forum here https://synopse.info/forum/viewtopic.php?pid=40358
Reintroduced code for ExtSelectClipRgn and fixed the TRect for bitmap in DrawBitmap.
> Reintroduce SelectClipRgn support for GDI+ and fix DrawBitmap()

- ex/mvc-blog/MVCServerFirebirdIbx.dpr
- src/db/mormot.db.sql.ibx.pas
Reported in forum by @vs: https://synopse.info/forum/viewtopic.php?pid=40879#p40879
> Fixes few minor typos

- src/soa/mormot.soa.codegen.pas
> SimpleClient bug-fix for pas2js and other clients. M1->M2 bugfix

- src/net/mormot.net.client.pas
> small typo

- src/ui/mormot.ui.pdf.pas
> Display OutputIntent on Acrobat Reader "Standards" tab #269

- src/lib/mormot.lib.curl.pas
- src/net/mormot.net.client.pas
Assorted updates I've been using for a while
> Update cURL API

- src/net/mormot.net.openapi.pas
Only supports references to schemas, not to responses or other types
> Handle simple OpenApi V3 specifications

- src/orm/mormot.orm.core.pas
In case you declare an ORM class with `Single` property, like this:
```delphi
TOrmCastleTransform = class(TOrm)
FTranslationX: Single;
published
property TranslationX: Single read FTranslationX write FTranslationX;
end;
```
the constructor of `TOrmModel` will fail with a helpful exception that `oftFloat/rkFloat` are not supported. (It would be even better if the exception message explicitly said that `Single` is not supported but `Double` is :) ).
However (if you run without debugger) it is easy to miss, because it is then obscured by another exception: an access violation occurs when destructor tries to access `TableProps[i].Props`, but `TableProps[i]` is `nil`.
This PR makes the destructor "robust", it will continue without causing a new exception when `TableProps[i] = nil`.
> Robust TOrmModel.Destroy, in case TableProps[i] = nil

- ex/rest-websockets/restws_SimpleEchoServer.dpr
Updated from same example in mORMot 1
> Create restws_SimpleEchoServer.dpr - sample taken from mORMot1 and updated

- src/net/mormot.net.acme.pas
To support zerossl.com ACME server we need to fix two issues:
First, zerossl.com require waiting for certificate. So we add new `FinalizeDomainRegistration` and wait loop on `CompleteDomainRegistration` after call to `FinalizeDomainRegistration` in `RegisterAndWait`.
Second, we add `externalAccountBinding` support to associate an ACME account with an existing account in zerossl.com.
These changes are split into two commit to simplify code review.
Discussion here:
https://synopse.info/forum/viewtopic.php?pid=44091
> Support for zerossl.com ACME server
